### ISSUE TITLE
Compile Error with groovy 20.10 kernel 5.8.0-25-generic

### ISSUE THREAD

**Issue by williamblair333** [xverizex/driver_tp_link_t4u#1]
Ok, it's not an issue because I'm on a different version / different kernel.  Would you take a look though?

Getting error just like this:   https://github.com/cilynx/rtl88x2bu/issues/72  I know what a header file is but I'm not certain I can fix it.  Patch cited here:  https://github.com/cilynx/rtl88x2bu/pull/58 

Suggestions?

/home/bill/Downloads/driver_tp_link_t4u-master/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /home/bill/Downloads/driver_tp_link_t4u-master/include/osdep_service_linux.h:48,
                 from /home/bill/Downloads/driver_tp_link_t4u-master/include/osdep_service.h:50,
                 from /home/bill/Downloads/driver_tp_link_t4u-master/include/drv_types.h:27,
                 from /home/bill/Downloads/driver_tp_link_t4u-master/core/rtw_cmd.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:290: /home/bill/Downloads/driver_tp_link_t4u-master/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1780: /home/bill/Downloads/driver_tp_link_t4u-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-25-generic'
make: *** [Makefile:1998: modules] Error 2

**Comment by xverizex** [comment]
this means that the same structure is defined in different files. I don't know how to help you. maybe a #define is defined somewhere, which does not need to be defined.

**Comment by williamblair333** [comment]
I pulled from another github repo that is similar to yours.  It allowed the
make to run.  But I kept getting prompted over and over for the ssid
password so something must still be wrong.  Thanks for replying.


Thank you,

William Blair | williamblair333@gmail.com | 317-690-6129

**Comment by xverizex** [comment]
I pulled new patch. Now it works.
