### ISSUE TITLE
compilation crash for 5.8.0-34-generic kernel version

### ISSUE THREAD

**Issue by Taranovskiy** [xverizex/driver_tp_link_t4u#2]
Огромное спасибо за работу! После очередного обновления версии ядра код перестал компилироваться.
1. Возможно ли это починить?
2. Обязательно ли производить установку после каждого обновления версии ядра?
Заранее спасибо за ответ.

![image](https://user-images.githubusercontent.com/22897018/104162509-c9137f80-5405-11eb-896e-e73f36154503.png)

**Comment by K3ler** [comment]
да, такая же фигня.

**Comment by xverizex** [comment]
Да, после новой версии ядра, надо устанавливать драйвер заного. я чуть позже посмотрю что изменилось и попробую исправить.

**Comment by xverizex** [comment]
в ядре linux такая же структура появилась. можно попробовать удалить её из драйвера адаптера и посмотреть что будет или поменять название в драйвере адаптера. надо посмотреть где это используется.  наверное всё таки лучше поменять в драйвере, потому что в драйвере больше элементов в структуре. щас сделаю.

**Comment by xverizex** [comment]
Всё сделал. Только извиняюсь сразу если будут глюк с linux. видите ли, я не разработчик ядра и не слежу за изменениями в ядре. есть такой момент здесь в функции os_dep/linux/ioctl_cfg80211.c:.update_mgmt_frame_registrations. тут поменялись аргументы, передаваемые в функцию и я не знаю что именно надо указать, так что попробовал то, что думаю правильно. и вот здесь также проблемка.
```
SET_CFG80211_REPORT_MGMT(pwdev_priv, IEEE80211_STYPE_PROBE_REQ, 1);
```
раньше сюда `reg` помещался вместо 1.
Так что извиняюсь, если что-то накосячил.

**Comment by xverizex** [comment]
но я протестировал и у меня работало. то есть подключение к wifi и заход на страницу.

**Comment by xverizex** [comment]
ну раз вопросов и подсказок нет, то закрываю issue.
