### ISSUE TITLE
Инструкции для ядра < 5.8

### ISSUE THREAD

**Issue by DanInSpace104** [xverizex/driver_tp_link_t4u#3]
Большое спасибо вам за адаптацию драйвера! Однако на версии 5.4 не работало, ломали изменения коммита d345911
Пришлось сделать checkout на c77953d и всё заработало. Может быть добавить инструкции об этом в README?

**Comment by xverizex** [comment]
да. но 5.4 версия это вроде как уже старая версия. или я случайно для ubuntu 21.04 делал. я позже ubuntu поставлю и гляну на 20.04. но вроде я как адаптирую под новые версии ядра, которые выходят для ubuntu 20.04.

**Comment by xverizex** [comment]
можете предложить pull или как он там называется, чтобы я добавил изменения в git. просто я не знаю что вы хотите добавить. предложите свою версию README и я её добавлю.
