### ISSUE TITLE
Compile error kernel 5.15.0-52-generic

### ISSUE THREAD

**Issue by Atryv** [xverizex/driver_tp_link_t4u#5]
Во-первых, выражаю огромную благодарность за проделанную работу!
Я пытался собрать драйвер на KDE neon 5.26 (Ubuntu 20.04) с ядром 5.15.0-52-generic, но получил такую ошибку:
`rtw_br_ext.c:20:11: fatal error: net/ipx.h: No such file or directory`

Немного покапавшись я наткнулся на подобную проблему в других драйверах: [https://github.com/lwfinger/rtl8723bu/issues/183](url). Она связана с тем, что модуль ipx.h был удален из новых версий ядра.

Возможно ли избавиться от него в Вашем коде?

**Comment by xverizex** [comment]
Очень жаль. Я занимался поддержкой, но я не слежу за изменениями в ядре. Боюсь что если что-то убрать без замены, то что-то перестанет работать. Я не разработчик ядра, я больше по user-space. Когда я купил wifi адаптер, был смысл исследовать и там были не такие страшные изменения, но теперь у меня просто времени не хватит этим заниматься. Может быть, если вы сами попробуете исправить и если у вас получиться, то сделайте pull request, я его приму.

**Comment by Atryv** [comment]
Вас понял, спасибо за ответ! 
Быть может действительно займусь этим.
